
import React, { createContext, useContext, useMemo, useCallback } from 'react';

type Language = 'vi';

const interpolate = (str: string, values: Record<string, any>): string => {
  return str.replace(/{(\w+)}/g, (match, key) => {
    return values[key] !== undefined ? String(values[key]) : match;
  });
};

const VI_TRANSLATIONS: Record<string, string> = {
  "header.title": "NHÓM THÂN HỬU PHÚ NHUẬN",
  "nav.home": "Trang chủ",
  "nav.members": "Thành viên",
  "nav.guests": "Khách mời",
  "nav.events": "Sự kiện",
  "adminMode": "Chế độ Admin",
  "home.welcome": "Chào mừng đến với",
  "home.history": "Lịch sử Hình thành",
  "home.mission": "Ý nghĩa & Mục tiêu",
  "home.keyEvents": "Các Sự kiện Quan trọng",
  "home.recentActivity": "Hoạt động gần đây",
  "home.groupSong": "Bài ca NHÓM THÂN HỬU PHÚ NHUẬN",
  "home.adminTools": "Công cụ Quản trị viên",
  "home.broadcastPrompt": "Gửi thông báo đến tất cả thành viên đã bật nhận tin.",
  "home.broadcastAction": "Gửi thông báo",
  "home.manageHero": "Quản lý ảnh bìa",
  "home.manageVideo": "Quản lý video",
  "edit": "Chỉnh sửa",
  "common.delete": "Xóa",
  "common.notUpdated": "Chưa cập nhật",
  "common.updateNeeded": "Vui lòng cập nhật thông tin chi tiết.",
  "common.new": "mới",
  "common.loading": "Đang tải...",
  "common.openInNewTab": "Mở trong tab mới",
  "common.saveSuccess": "Dữ liệu đã được lưu an toàn!",
  "common.expand": "Mở rộng giao diện",
  "common.collapse": "Thu gọn giao diện",
  "common.undo": "Hoàn tác",
  "common.redo": "Làm lại",
  "members.title": "Thành viên chính thức (Thân Hữu)",
  "guests.title": "Khách mời & Cộng tác viên",
  "events.title": "Sự kiện & Hoạt động",
  "add.member": "Thêm thành viên mới",
  "add.guest": "Thêm khách mời mới",
  "add.event": "Thêm sự kiện mới",
  "memberCard.viewDetails": "Xem chi tiết",
  "memberCard.editProfile": "Chỉnh sửa hồ sơ",
  "memberCard.shareProfile": "Chia sẻ hồ sơ của {name}",
  "memberCard.share": "Chia sẻ",
  "eventCard.viewDetails": "Xem chi tiết & Tóm tắt AI",
  "eventCard.hasYoutube": "Có video YouTube",
  "eventCard.hasVideo": "Có video",
  "eventCard.hasAudio": "Có audio",
  "modal.edit": "Chỉnh sửa: {name}",
  "modal.editContent": "Chỉnh sửa: {title}",
  "modal.addMember": "Thêm Thành viên mới",
  "modal.addGuest": "Thêm Khách mời mới",
  "modal.addEvent": "Thêm sự kiện mới",
  "modal.close": "Đóng",
  "form.name": "Tên",
  "form.role": "Vị trí",
  "form.profession": "Nghề nghiệp",
  "form.email": "Email",
  "form.address": "Địa chỉ",
  "form.description": "Mô tả",
  "form.joinedDate": "Ngày tham gia",
  "form.eventName": "Tên sự kiện",
  "form.eventDate": "Ngày diễn ra",
  "form.location": "Địa điểm",
  "form.youtubeUrl": "Đường dẫn Video YouTube (Tùy chọn)",
  "form.enterYoutubeUrl": "Nhập đường dẫn video YouTube",
  "form.enterWebUrl": "Nhập đường dẫn URL từ web",
  "form.youtubeValid": "Đường dẫn YouTube hợp lệ.",
  "form.youtubeInvalid": "Đường dẫn YouTube không hợp lệ.",
  "form.webInvalid": "Đường dẫn URL không hợp lệ.",
  "form.mediaManager": "Quản lý Media",
  "form.images": "Hình ảnh",
  "form.videos": "Videos",
  "form.audios": "Audios",
  "form.cancel": "Hủy",
  "form.save": "Cập nhật & Lưu lại",
  "form.updateProfile": "CẬP NHẬT CHỈNH SỬA",
  "form.add": "Thêm & Lưu lại",
  "form.addMember": "Thêm thành viên",
  "form.addEvent": "Thêm sự kiện",
  "form.activities": "Hoạt động đã tham gia",
  "form.addActivity": "Thêm hoạt động",
  "form.activityPlaceholder": "Nhập tên hoạt động...",
  "memberDetails.description": "Mô tả",
  "memberDetails.profession": "Nghề nghiệp",
  "memberDetails.email": "Email",
  "memberDetails.address": "Địa chỉ",
  "memberDetails.joinedDate": "Ngày tham gia",
  "memberDetails.activities": "Hoạt động đã tham gia",
  "memberDetails.noActivities": "Chưa có hoạt động nào được ghi nhận.",
  "memberDetails.loginCodeTitle": "Mã đăng nhập của bạn:",
  "memberDetails.generateNewCode": "Tạo mã mới",
  "memberDetails.copyCode": "Sao chép mã",
  "eventDetails.aiSummaryTitle": "Tóm tắt sự kiện bằng AI",
  "eventDetails.generateSummary": "Tạo tóm tắt",
  "eventDetails.generating": "Đang xử lý...",
  "eventDetails.aiThinking": "AI đang suy nghĩ...",
  "eventDetails.aiPrompt": "Nhấn nút bên dưới để tạo một bản tóm tắt ngắn gọn và hấp dẫn cho sự kiện này.",
  "eventDetails.video": "Video Sự kiện",
  "eventDetails.watchOnYoutube": "Xem video trên YouTube",
  "eventDetails.gallery": "Thư viện Media",
  "eventCard.description": "Mô tả chi tiết",
  "eventCard.otherImages": "Hình ảnh khác",
  "settings.title": "Cài đặt Hệ thống",
  "settings.displayMode": "Chế độ hiển thị",
  "settings.theme": "Chủ đề màu sắc",
  "settings.fontFamily": "Phông chữ",
  "settings.fontSize": "Cỡ chữ",
  "settings.language": "Ngôn ngữ",
  "settings.apiConfiguration": "Cấu hình API Key",
  "settings.geminiKey": "Gemini API Key",
  "settings.openaiKey": "OpenAI API Key",
  "settings.getKey": "Lấy API Key",
  "settings.keyPlaceholder": "Nhập API Key của bạn...",
  "settings.keySaved": "Đã lưu!",
  "theme.light": "Sáng",
  "theme.dark": "Tối",
  "theme.contrast": "Tương phản",
  "theme.indigo": "Chàm (Mặc định)",
  "theme.teal": "Xanh mòng két",
  "theme.rose": "Hồng",
  "theme.slate": "Xám đen",
  "theme.green": "Xanh lá",
  "theme.orange": "Cam",
  "theme.purple": "Tím",
  "font.inter": "Inter (Mặc định)",
  "font.roboto": "Roboto",
  "font.lora": "Lora",
  "font.poppins": "Poppins",
  "font.playfair": "Playfair",
  "font.arial": "Arial",
  "font.times": "Times New Roman / VnTime",
  "font.system": "Hệ thống",
  "fontSize.xs": "Rất nhỏ",
  "fontSize.sm": "Nhỏ",
  "fontSize.base": "Vừa (Mặc định)",
  "fontSize.lg": "Lớn",
  "fontSize.xl": "Rất lớn",
  "error.summary": "Không thể tạo tóm tắt. Vui lòng kiểm tra API Key trong Cài đặt.",
  "error.missingKey": "Vui lòng nhập API Key trong phần Cài đặt để sử dụng tính năng này.",
  "notifications.unsupported": "Trình duyệt của bạn không hỗ trợ thông báo.",
  "notifications.grantedTitle": "Thông báo đã được bật!",
  "notifications.grantedBody": "Bạn sẽ nhận được thông báo về các hoạt động mới của nhóm.",
  "notifications.denied": "Bạn đã chặn thông báo. Vui lòng vào cài đặt trình duyệt để cho phép.",
  "notifications.enable": "Bật thông báo",
  "notifications.enabled": "Thông báo đã được bật",
  "notifications.blocked": "Thông báo đã bị chặn. Vui lòng thay đổi trong cài đặt trình duyệt.",
  "notifications.newEventTitle": "Sự kiện Mới!",
  "notifications.newEventBody": "Một sự kiện mới vừa được tạo: \"{eventName}\". Nhấn để xem chi tiết!",
  "gemini.eventSummaryPrompt": "Bạn là một chuyên gia truyền thông. Hãy viết một bản tóm tắt ngắn gọn và hấp dẫn (khoảng 3-4 câu) cho sự kiện sau để đăng lên mạng xã hội.\n\nTên sự kiện: \"{eventName}\"\nMô tả: \"{eventDescription}\"\n\nTập trung vào không khí và ý nghĩa của sự kiện.\nQUAN TRỌNG: Phản hồi BẮT BUỘC phải bằng tiếng Việt.",
  "login.title": "Đăng nhập Thành viên",
  "login.titleAdmin": "Xác thực Admin",
  "login.cta": "Đăng nhập TV và KM",
  "login.logout": "Đăng xuất",
  "login.code": "Mã đăng nhập",
  "login.codePlaceholder": "Nhập mã do Admin cung cấp",
  "login.invalidCode": "Mã đăng nhập không hợp lệ hoặc không tồn tại.",
  "login.notAdmin": "Tài khoản này không có quyền Admin.",
  "login.password": "Mật khẩu Admin",
  "login.enterPassword": "Nhập mật khẩu",
  "login.createPassword": "Tạo mật khẩu Admin",
  "login.confirmPassword": "Xác nhận mật khẩu",
  "login.passwordMismatch": "Mật khẩu không khớp.",
  "login.passwordWrong": "Mật khẩu không chính xác.",
  "login.passwordCreated": "Đã tạo mật khẩu thành công.",
  "login.passwordChanged": "Đã đổi mật khẩu thành công.",
  "login.setupPrompt": "Chưa có mật khẩu Admin. Vui lòng tạo mật khẩu mới để bảo vệ quyền quản trị.",
  "login.changePassword": "Đổi mật khẩu Admin",
  "login.newPassword": "Mật khẩu mới",
  "login.userPrompt": "Vui lòng nhập mã thành viên do Admin cung cấp để đăng nhập.",
  "confirm.deleteTitle": "Xác nhận Xóa",
  "confirm.deleteMember": "Bạn có chắc chắn muốn xóa thành viên {name} không? Hành động này không thể hoàn tác.",
  "confirm.confirmDelete": "Xác nhận Xóa",
  "confirm.deleteEventTitle": "Xác nhận Xóa Sự kiện",
  "confirm.deleteEvent": "Bạn có chắc chắn muốn xóa sự kiện {name} không? Hành động này không thể hoàn tác.",
  "memberType.member": "Thành viên",
  "memberType.guest": "Khách mời",
  "activity.added": "Đã thêm",
  "activity.noActivity": "Chưa có hoạt động nào gần đây.",
  "time.yearsAgo": "{count} năm trước",
  "time.monthsAgo": "{count} tháng trước",
  "time.daysAgo": "{count} ngày trước",
  "time.hoursAgo": "{count} giờ trước",
  "time.minutesAgo": "{count} phút trước",
  "time.justNow": "Vài giây trước",
  "calendar.prevMonth": "Tháng trước",
  "calendar.nextMonth": "Tháng sau",
  "calendar.addEventOn": "Thêm sự kiện vào ngày {date}",
  "clipboard.copy": "Sao chép nội dung",
  "clipboard.copied": "Đã sao chép!",
  "clipboard.copyFailed": "Sao chép thất bại!",
  "clipboard.unsupported": "Không thể sao chép. Trình duyệt của bạn không hỗ trợ tính năng này.",
  "bulkadd.title": "Thêm hàng loạt {memberType}",
  "bulkadd.dragDrop": "Kéo và thả ảnh vào đây",
  "bulkadd.clickToSelect": "hoặc nhấn để chọn tệp",
  "bulkadd.multiSelect": "Bạn có thể chọn nhiều ảnh cùng lúc",
  "bulkadd.selectedImages": "Ảnh đã chọn ({count}):",
  "bulkadd.deleteImage": "Xóa ảnh",
  "bulkadd.addMembers": "Thêm {count} {memberType}",
  "broadcast.title": "Gửi thông báo chung",
  "broadcast.formTitle": "Tiêu đề",
  "broadcast.formTitlePlaceholder": "VD: Nhắc nhở quan trọng",
  "broadcast.formMessage": "Nội dung",
  "broadcast.formMessagePlaceholder": "Nhập nội dung thông báo của bạn tại đây...",
  "broadcast.send": "Gửi thông báo",
  "heroManager.title": "Quản lý ảnh bìa động",
  "heroManager.prompt": "Thêm hoặc xóa các ảnh sẽ được hiển thị trong slideshow trên trang chủ.",
  "heroManager.addImage": "Thêm ảnh",
  "socialManager.title": "Quản lý Liên kết Mạng xã hội & Website",
  "socialManager.facebook": "URL Facebook",
  "socialManager.zalo": "URL Zalo",
  "socialManager.viber": "URL Viber",
  "socialManager.website": "URL Website",
  "videoManager.title": "Quản lý Bài ca NHÓM THÂN HỬU PHÚ NHUẬN",
  "videoManager.preview": "Xem trước & Ảnh nền",
  "videoManager.previewFailed": "Không thể xem trước video.",
  "videoManager.youtubeLinked": "Video YouTube đã được liên kết.",
  "videoManager.noPreview": "Bản xem trước không có sẵn trong cửa sổ này.",
  "videoManager.noVideo": "Chưa có video được chọn",
  "videoManager.youtubeUrl": "Đường dẫn video YouTube",
  "videoManager.webUrl": "URL Video từ Web",
  "videoManager.or": "hoặc",
  "videoManager.upload": "Tải lên tệp video từ máy tính",
  "videoManager.save": "Lưu",
  "videoManager.customThumbnail": "Ảnh nền video (Thumbnail)",
  "videoManager.uploadThumbnail": "Tải ảnh nền lên",
  "videoManager.useDefaultThumbnail": "Dùng ảnh mặc định YouTube",
  "videoManager.watchOnYoutube": "Xem trên YouTube",
  "sort.sortBy": "Sắp xếp:",
  "sort.manual": "Thủ công (Kéo thả)",
  "sort.nameAsc": "Tên (A-Z)",
  "sort.nameDesc": "Tên (Z-A)",
  "sort.role": "Cấp bậc/Vai trò",
  "sort.joinedDateNewest": "Ngày tham gia (Mới nhất)",
  "sort.joinedDateOldest": "Ngày tham gia (Cũ nhất)",
  "sort.dateNewest": "Mới nhất",
  "sort.dateOldest": "Cũ nhất",
  "search.placeholder": "Tìm kiếm theo tên hoặc nghề nghiệp...",
  "media.filter": "Lọc theo loại:",
  "media.all": "Tất cả",
  "media.image": "Hình ảnh",
  "media.video": "Video",
  "media.audio": "Audio/Nhạc",
  "media.youtube": "YouTube",
  "media.web": "Web Link",
  "admin.tool": "Công cụ Admin",
  "admin.dashboardTitle": "Bảng điều khiển Quản trị viên",
  "admin.quickActions": "Tác vụ nhanh",
  "admin.exportData": "Xuất dữ liệu dự phòng (JSON)",
  "admin.exportDataDesc": "Tải về toàn bộ thông tin để lưu trữ riêng.",
  "admin.importData": "Khôi phục dữ liệu",
  "admin.importDataDesc": "Nhập tệp JSON đã tải về để khôi phục.",
  "admin.changePassword": "Đổi mật khẩu Admin",
  "admin.changePasswordDesc": "Thay đổi mật khẩu đăng nhập chế độ Admin.",
  "guide.title": "Hướng dẫn chỉnh sửa thành viên 👍",
  "guide.tabMember": "Dành cho Thành viên",
  "guide.tabAdmin": "Dành cho Trưởng nhóm",
  "guide.intro": "Để cập nhật thông tin cá nhân của bạn, vui lòng thực hiện theo các bước sau:",
  "guide.adminIntro": "Quy trình quản lý và tổng hợp dữ liệu dành cho Trưởng nhóm:",
  "guide.step": "Phần",
  "guide.step1Title": "Thông tin từ Admin",
  "guide.step1Desc": "Trưởng nhóm (Admin) sẽ cung cấp link của ứng dụng và mật khẩu (mã thành viên) để đăng nhập.",
  "guide.step2Title": "Bắt đầu chỉnh sửa 👍",
  "guide.step2Desc": "Click vào menu 'Thành viên', click vào nút 'Đăng nhập', sau đó nhập mật khẩu (mã) do Trưởng nhóm cung cấp.",
  "guide.step3Title": "Thực hiện cập nhật",
  "guide.step3Desc": "Tìm đến thẻ tên của bạn, nhấn 'Chỉnh sửa hồ sơ' và thay đổi thông tin theo hướng dẫn trên màn hình.",
  "guide.step4Title": "Hoàn tất & Lưu file .json",
  "guide.step4Desc": "Click vào nút 'CẬP NHẬT CHỈNH SỬA' - chọn 'OK' để hệ thống lưu tệp .json vào thư mục tải về trên thiết bị của bạn.",
  "guide.step5Title": "Gửi dữ liệu cho Admin",
  "guide.step5Desc": "Copy file .json đã tải về và gửi cho Trưởng nhóm để cập nhật chính thức lên hệ thống.",
  "guide.adminStep1Title": "Kích hoạt quyền Admin",
  "guide.adminStep1Desc": "Bật công tắc 'Admin' trên menu và nhập mật khẩu quản trị để truy cập các tính năng nâng cao.",
  "guide.adminStep2Title": "Quản lý nội dung",
  "guide.adminStep2Desc": "Trưởng nhóm có toàn quyền sửa: lịch sử, sứ mệnh, thành viên, khách mời, sự kiện và gửi thông báo chung.",
  "guide.adminStep3Title": "Cung cấp mã đăng nhập",
  "guide.adminStep3Desc": "Click vào 'Xem chi tiết' của từng người để copy 'Mã đăng nhập'. Sau đó gửi Link app + Mã này cho họ.",
  "guide.adminStep4Title": "Thành viên tự sửa",
  "guide.adminStep4Desc": "Thành viên làm theo hướng dẫn (nút ?) để tự sửa thông tin và xuất file .json gửi lại cho bạn.",
  "guide.adminStep5Title": "Tổng hợp dữ liệu",
  "guide.adminStep5Desc": "Vào 'Công cụ Admin' -> 'Khôi phục dữ liệu'. Chọn lần lượt các file .json thành viên gửi để cập nhật vào hệ thống.",
  "guide.outro": "Sau khi hoàn tất chỉnh sửa, bạn vẫn có thể xem thông tin các nội dung khác của ứng dụng bình thường.",
  "guide.gotIt": "Đã hiểu & Bắt đầu"
};

interface LanguageContextType {
  language: Language;
  t: (key: string, values?: Record<string, any>) => string;
  isLoaded: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const t = useCallback((key: string, values?: Record<string, any>): string => {
    const message = VI_TRANSLATIONS[key] || key;
    return values ? interpolate(message, values) : message;
  }, []);

  const value = useMemo(() => ({
    language: 'vi' as const,
    t,
    isLoaded: true 
  }), [t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
